version: 1

sources:
  - name: rawData
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product_copy
      - name: ship
        identifier: raw_gz_ship_copy
      - name: sales
        identifier: raw_gz_sales
